FROM alpine:3.9

ARG GUID
ENV GUID=1000

# COPY sudoers /etc/

RUN apk --update add bash wget dpkg-dev sudo 

RUN apk update && \
    apk add sudo && \
    adduser -u $GUID -G wheel -D alpine && \
    rm -rf /var/cache/apk/*

RUN echo "root:root" | chpasswd
RUN echo "alpine:alpine" | chpasswd

USER alpine
